FROM hasura/graphql-engine:v2.36.3.cli-migrations-v3
ENV HASURA_GRAPHQL_ENABLE_CONSOLE=true
ENV HASURA_GRAPHQL_DEV_MODE=false
ENV HASURA_GRAPHQL_PG_CONNECTIONS=15

CMD HASURA_GRAPHQL_METADATA_DATABASE_URL=$DATABASE_URL HASURA_GRAPHQL_DATABASE_URL=$DATABASE_URL graphql-engine \
    serve \
    --server-port $PORT
